export const GET_QUESTIONS = 'GET_QUESTIONS'
export const GET_QUESTIONS_LOADING = 'GET_QUESTIONS_LOADING'
export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS'
export const GET_QUESTIONS_ERROR = 'GET_QUESTIONS_ERROR'

export const SET_SELECTED_QUESTION = 'SET_SELECTED_QUESTION'
